<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>Entity-specific audit providers for MillWorks AuditCore</Description>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.5" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MillWorks.AuditCore.Abstractions\MillWorks.AuditCore.Abstractions.csproj" />
    </ItemGroup>

</Project>
