// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MillWorks.AuditCore.EntityFramework.Data;

#nullable disable

namespace MillWorks.AuditCore.EntityFramework.Migrations
{
    [DbContext(typeof(AuditApplicationDbContext))]
    [Migration("20260402194349_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditArchiveRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchiveId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ArchiveId")
                        .HasJsonPropertyName("archive_id");

                    b.Property<string>("ArchiveVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("1.0")
                        .HasColumnName("ArchiveVersion")
                        .HasJsonPropertyName("archive_version");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BlobName")
                        .HasJsonPropertyName("blob_name");

                    b.Property<string>("CompressionType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("gzip")
                        .HasColumnName("CompressionType")
                        .HasJsonPropertyName("compression_type");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ContainerName")
                        .HasJsonPropertyName("container_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)")
                        .HasColumnName("CreatedByUserId")
                        .HasJsonPropertyName("created_by_user_id");

                    b.Property<DateTimeOffset>("DateRangeEnd")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DateRangeEnd")
                        .HasJsonPropertyName("date_range_end");

                    b.Property<DateTimeOffset>("DateRangeStart")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DateRangeStart")
                        .HasJsonPropertyName("date_range_start");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ErrorMessage")
                        .HasJsonPropertyName("error_message");

                    b.Property<int>("EventCount")
                        .HasColumnType("int")
                        .HasColumnName("EventCount")
                        .HasJsonPropertyName("event_count");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("Hash")
                        .HasJsonPropertyName("hash");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastVerifiedAt")
                        .HasJsonPropertyName("last_verified_at");

                    b.Property<string>("Metadata")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Metadata")
                        .HasJsonPropertyName("metadata");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("SizeBytes")
                        .HasJsonPropertyName("size_bytes");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Status")
                        .HasJsonPropertyName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId")
                        .IsUnique()
                        .HasDatabaseName("IX_Archive_Record_ArchiveId");

                    b.HasIndex("ContainerName")
                        .HasDatabaseName("IX_Archive_Record_ContainerName");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Archive_Record_CreatedAt");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("IX_Archive_Record_CreatedByUserId");

                    b.HasIndex("LastVerifiedAt")
                        .HasDatabaseName("IX_Archive_Record_LastVerifiedAt");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Archive_Record_Status");

                    b.HasIndex("DateRangeStart", "DateRangeEnd")
                        .HasDatabaseName("IX_Archive_Record_DateRange");

                    b.ToTable("ArchiveRecord", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_ArchiveRecord_DateRange", "[DateRangeEnd] >= [DateRangeStart]");
                        });
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId")
                        .HasJsonPropertyName("event_id");

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Action")
                        .HasJsonPropertyName("action");

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AdditionalData")
                        .HasJsonPropertyName("additional_data");

                    b.Property<string>("AspNetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AspNetUserId")
                        .HasJsonPropertyName("asp_net_user_id");

                    b.Property<string>("AssemblyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AssemblyName")
                        .HasJsonPropertyName("assembly_name");

                    b.Property<string>("CallingMethodName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("CallingMethodName")
                        .HasJsonPropertyName("calling_method_name");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("CorrelationId")
                        .HasJsonPropertyName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Duration")
                        .HasColumnType("int")
                        .HasColumnName("Duration")
                        .HasJsonPropertyName("duration");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("EndDate")
                        .HasJsonPropertyName("end_date");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasJsonPropertyName("entity_id");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EntityType")
                        .HasJsonPropertyName("entity_type");

                    b.Property<string>("Environment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Production")
                        .HasColumnName("Environment")
                        .HasJsonPropertyName("environment");

                    b.Property<string>("EventType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EventType")
                        .HasJsonPropertyName("event_type");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("InsertedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("InsertedDate")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasJsonPropertyName("inserted_date");

                    b.Property<int>("IntegrityStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("IntegrityStatus")
                        .HasJsonPropertyName("integrity_status");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("IpAddress")
                        .HasJsonPropertyName("ip_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JsonData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JsonData")
                        .HasJsonPropertyName("json_data");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastUpdatedDate")
                        .HasJsonPropertyName("last_updated_date");

                    b.Property<string>("MachineName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MachineName")
                        .HasJsonPropertyName("machine_name");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("RequestMethod")
                        .HasJsonPropertyName("request_method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RequestPath")
                        .HasJsonPropertyName("request_path");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("StartDate")
                        .HasJsonPropertyName("start_date");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId")
                        .HasJsonPropertyName("tenant_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("User")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("User")
                        .HasJsonPropertyName("user");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("UserAgent")
                        .HasJsonPropertyName("user_agent");

                    b.Property<string>("UserEnvName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("UserEnvName")
                        .HasJsonPropertyName("user_env_name");

                    b.Property<string>("UserFullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("UserFullName")
                        .HasJsonPropertyName("user_full_name");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AppUserId")
                        .HasJsonPropertyName("app_user_id");

                    b.HasKey("EventId");

                    b.HasIndex("EventType", "InsertedDate")
                        .HasDatabaseName("IX_AuditEvents_EventType_Date_Filtered")
                        .HasFilter("[EventType] IS NOT NULL");

                    b.HasIndex(new[] { "AspNetUserId" }, "IX_AuditEvents_AspNetUserId");

                    b.HasIndex(new[] { "CorrelationId" }, "IX_AuditEvents_CorrelationId");

                    b.HasIndex(new[] { "InsertedDate", "EventType" }, "IX_AuditEvents_Date_Type");

                    b.HasIndex(new[] { "EntityType", "EntityId" }, "IX_AuditEvents_Entity");

                    b.HasIndex(new[] { "EventType" }, "IX_AuditEvents_EventType");

                    b.HasIndex(new[] { "IntegrityStatus" }, "IX_AuditEvents_IntegrityStatus");

                    b.HasIndex(new[] { "TenantId" }, "IX_AuditEvents_TenantId");

                    b.HasIndex(new[] { "UserId" }, "IX_AuditEvents_UserId");

                    b.ToTable("AuditEvents", "audit");
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditIntegrityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlgorithmVersion")
                        .HasColumnType("int")
                        .HasColumnName("AlgorithmVersion");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("varchar(44)")
                        .HasColumnName("Checksum");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DigitalSignature")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("DigitalSignature");

                    b.Property<string>("EventHash")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("varchar(44)")
                        .HasColumnName("EventHash");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId");

                    b.Property<string>("HmacSignature")
                        .HasMaxLength(44)
                        .HasColumnType("varchar(44)")
                        .HasColumnName("HmacSignature");

                    b.Property<string>("Parameters")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("Parameters");

                    b.Property<string>("PreviousEventHash")
                        .HasMaxLength(44)
                        .HasColumnType("varchar(44)")
                        .HasColumnName("PreviousEventHash");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("SequenceNumber");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SequenceNumber"));

                    b.Property<DateTimeOffset>("TrustedTimestamp")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("TrustedTimestamp");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "IX_AuditIntegrity_EventId")
                        .IsUnique();

                    b.HasIndex(new[] { "EventHash", "PreviousEventHash" }, "IX_AuditIntegrity_HashChain");

                    b.HasIndex(new[] { "SequenceNumber" }, "IX_AuditIntegrity_SequenceNumber")
                        .IsUnique();

                    b.HasIndex(new[] { "TrustedTimestamp" }, "IX_AuditIntegrity_Timestamp");

                    b.ToTable("AuditIntegrity", "audit");
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditIntegrityWorkItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int")
                        .HasColumnName("AttemptCount")
                        .HasJsonPropertyName("attempt_count");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CompletedAt")
                        .HasJsonPropertyName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasJsonPropertyName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EventId")
                        .HasJsonPropertyName("event_id");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LastAttemptAt")
                        .HasJsonPropertyName("last_attempt_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("LastError")
                        .HasJsonPropertyName("last_error");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("LeaseExpiresAt")
                        .HasJsonPropertyName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("LeaseOwner")
                        .HasJsonPropertyName("lease_owner");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("Status")
                        .HasJsonPropertyName("status");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventId" }, "IX_IntegrityWorkItems_EventId")
                        .IsUnique();

                    b.HasIndex(new[] { "LeaseExpiresAt" }, "IX_IntegrityWorkItems_LeaseExpiry");

                    b.HasIndex(new[] { "Status" }, "IX_IntegrityWorkItems_Status");

                    b.HasIndex(new[] { "Status", "CreatedAt" }, "IX_IntegrityWorkItems_Status_CreatedAt");

                    b.ToTable("AuditIntegrityWorkItems", "audit");
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("Action");

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("AdditionalData");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)")
                        .HasColumnName("CorrelationId");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("EntityId");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EntityType");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("NewValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("NewValue");

                    b.Property<string>("OldValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("OldValue");

                    b.Property<string>("PropertyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PropertyName");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("UserAgent");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Action" }, "IX_AuditLogs_Action");

                    b.HasIndex(new[] { "CorrelationId" }, "IX_AuditLogs_CorrelationId");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_AuditLogs_CreatedAt");

                    b.HasIndex(new[] { "CreatedById" }, "IX_AuditLogs_CreatedBy");

                    b.HasIndex(new[] { "CreatedAt", "EntityName" }, "IX_AuditLogs_Date_Entity");

                    b.HasIndex(new[] { "EntityName", "EntityId" }, "IX_AuditLogs_Entity");

                    b.ToTable("AuditLogs", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLogs_Action", "[Action] >= 0 AND [Action] <= 10");
                        });
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditSecurityEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Details");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("DetectedAt");

                    b.Property<string>("DetectedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("DetectedBy");

                    b.Property<int>("EventType")
                        .HasColumnType("int")
                        .HasColumnName("EventType");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("IpAddress");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Message");

                    b.Property<Guid?>("RelatedAuditEventId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RelatedAuditEventId");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ResolvedAt");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ResolvedBy");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Severity")
                        .HasColumnType("int")
                        .HasColumnName("Severity");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RelatedAuditEventId");

                    b.HasIndex(new[] { "DetectedAt" }, "IX_SecurityEvents_DetectedAt");

                    b.HasIndex(new[] { "EventType" }, "IX_SecurityEvents_EventType");

                    b.HasIndex(new[] { "Severity" }, "IX_SecurityEvents_Severity");

                    b.HasIndex(new[] { "Status" }, "IX_SecurityEvents_Status");

                    b.ToTable("SecurityEvents", "audit");
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditIntegrityEntity", b =>
                {
                    b.HasOne("MillWorks.AuditCore.EntityFramework.Entities.AuditEventEntity", "AuditEvent")
                        .WithOne("AuditIntegrity")
                        .HasForeignKey("MillWorks.AuditCore.EntityFramework.Entities.AuditIntegrityEntity", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEvent");
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditIntegrityWorkItemEntity", b =>
                {
                    b.HasOne("MillWorks.AuditCore.EntityFramework.Entities.AuditEventEntity", "AuditEvent")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditEvent");
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditSecurityEventEntity", b =>
                {
                    b.HasOne("MillWorks.AuditCore.EntityFramework.Entities.AuditEventEntity", "RelatedAuditEvent")
                        .WithMany()
                        .HasForeignKey("RelatedAuditEventId");

                    b.Navigation("RelatedAuditEvent");
                });

            modelBuilder.Entity("MillWorks.AuditCore.EntityFramework.Entities.AuditEventEntity", b =>
                {
                    b.Navigation("AuditIntegrity");
                });
#pragma warning restore 612, 618
        }
    }
}
